DROP TABLE IF EXISTS EVENTS;

CREATE TABLE EVENTS(
  EVENT_ID INT,
  TITLE VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(300),
  LOCATION VARCHAR(70),
  START_DATE timestamp default CURRENT_TIMESTAMP,
  END_DATE timestamp default CURRENT_TIMESTAMP,
  constraint event_id_pk PRIMARY KEY (EVENT_ID),
  constraint title_constraint UNIQUE (TITLE));

